# Generated by Django 4.1.1 on 2022-09-17 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updateAt', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=True)),
                ('isRefund', models.BooleanField(default=True)),
                ('method', models.IntegerField(choices=[(1, 'Debit/Credit cards'), (2, 'EMI'), (3, 'UPI'), (4, 'CASH ON DELIVERY')], default=4)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updateAt', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField(default=1)),
                ('success', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.payment')),
                ('product', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
